### ISSUE TITLE
vote requests appear multiple times on home screen

### ISSUE THREAD

**Issue by aakil786** [grassrootza/grassroot-platform#14]
looks like it is being duplicated, in the display, need to see what the query returns.

**Comment by luke-grassroot** [comment]
As noted on other repo, I can't replicate this. Neither on production nor on localhost. Screenshot from home page on production right after calling a vote attached,
<img width="1057" alt="screenshot-home-page-vote-duplication" src="https://cloud.githubusercontent.com/assets/11020273/11056261/939ed25e-8788-11e5-99ad-897adb71786c.PNG">

**Comment by aakil786** [comment]
ok could be the fact that i have many groups on my local database, will see if it plays a role, will debug

**Comment by aakil786** [comment]
fixed
