### ISSUE TITLE
Account entity ID not being generated

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#23]
Via 'admin/accounts/create', posting, get this log error:

org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
  Detail: Failing row contains (null, 2015-11-13 23:05:49.053, Test, null, t, t, t).

**Comment by luke-grassroot** [comment]
Call route is accountManagementService.createAccount(String accountName)

**Comment by aakil786** [comment]
will have a look

**Comment by aakil786** [comment]
account entity and account repository looks fine, passes a simple save test

**Comment by aakil786** [comment]
service test also passes :-(

    @Test
    public void shouldSaveBilling() {
        String email = "bigbucks@money.com";
        Account account = accountManagementService.createAccount("branch1");
        account = accountManagementService.setBillingEmail(account, email);
        assertNotEquals(null,account.getId());
        assertEquals("bigbucks@money.com",account.getPrimaryEmail());
    }

**Comment by aakil786** [comment]
will have to make myself an administrator so i can test the web page

**Comment by luke-grassroot** [comment]
I am also writing tests in core (really big bloops on my part not to have done earlier) and the repository is passing. So the problem isn't in Hibernate/JPA, it must be in the DB (since this only causes a problem in local_pg). Maybe I messed something up in creating/assigning the sequences?

**Comment by luke-grassroot** [comment]
Fixed by latest commit recreating table.
