### ISSUE TITLE
Create vote default expiry time to something in the future

### ISSUE THREAD

**Issue by aakil786** [grassrootza/grassroot-platform#3]
Maybe current time plus 1 hour, otherwise if the user does not change it it will expire before anyone can vote. Not sure if create meeting has the same problem.

**Comment by luke-grassroot** [comment]
Yes, that makes sense. One hour is probably best. No need with meeting I don't think.

**Comment by luke-grassroot** [comment]
Okay the datetimepicker is misbehaving, not acting predictably when setting both defaultDate and minDate, so am going to just use minDate as in the future -- but then can't do one hour, in case user wants it quicker, so 5 mins in the future. Going to have to revisit when fix the dateTimePicker overall. Will close on next commit.
