### ISSUE TITLE
Create entity for logbook

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#38]
Example of simple, likely most common user flow:

-- After a meeting (though not necessarily), a group organizer or member records a decision, such as "X will do Y", with a date & time Z, linked to the group

-- From then, anyone in the group can see that this decision has been recorded in the logbook, sorted by newest first, and categorized by "still to finish" vs "finished"

-- Users with the right permissions can mark that "this item is now done" (i.e., finished)

-- At date & time Z (or a few days before it), a reminder is sent to the group that this logbook entry is not yet marked finished

-- If no one marks it done by Z, it is reset to Z + 1 week, and the reminder is sent out again the subsequent week (this extension can also be manually triggered)

More complex uses / nuances:

-- In the future, may want to make explicit the link to the group member assigned (at first, can just hold a text string, i.e., "X will do it" is in the text string)

-- If I am a coordinator of a group with a number of sub-groups, I may want to create logbook entries in each of the subgroups, with these being distinct (i.e., the entry is replicated, not just the parent's item reflected in the subgroup), but with these traceable back to the parent group's entry (so, e.g., I can see, "which groups have completed this and which have not", and so on).

As this is probably the function where we are least certain of use, and there is the highest likelihood of significant alteration in the future, it will be good to start with the fairly simple and then add to it later.

**Comment by aakil786** [comment]
created entity, need to do all the queries, service methods and reminders logic

**Comment by aakil786** [comment]
committed entity so that I don't have to merge scripts. Heaving some issues testing some of the services, will test it via the rest api, before carrying on with the rest of services and reminders

**Comment by luke-grassroot** [comment]
Making entity as closed for now as most of it is there, going to create more specific issues for follow ups.
