### ISSUE TITLE
Optimize USSD opening menu queries (cut down DB queries)

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#54]
The start menu on the USSD interface does quite a bit of work, which means that at present it is generating a number of DB calls -- a recipe for performance problems.

The methods that make the calls are in USSDHomeContoller, especially the startMenu(), userResponseNeeded(), and requestUserResponse() methods.

The first one does a check if the user has to respond to anything, being one of four possible options:

1 -- Has to respond to a vote
2 -- Has to respond to a meeting request
3 -- Has to name (or deactivate) a recently created group
4 -- Has to name themselves as a user
(5 -- In future, has to mark if a logbook action assigned to them is completed or not, near/after its due date)

At present, this is done by, first, in userResponseNeeded(), calling service methods that return a boolean, "true" if any of the responses is needed. Then in requestUserResponse() it checks which of the responses are needed and constructs an opening menu accordingly.

One obvious improvement is to merge the two into one call, so userResponseNeeded() returns a USSDResponse Enum (Response.NONE if no response), which is then passed to requestResponse(). That is straightforward and assigned to lsj.

That still though leaves four calls in responseNeeded, and possibly an extra call in the menu construction (to get vote or meeting details).

To cut them down, we may/possibly need an advanced query that checks all conditions at once and returns a false if none are true, and/or returns an integer depending which works? Or some other method ... However done, we do need to cut this down.

**Comment by luke-grassroot** [comment]
As discussed in today's meeting, further specifying where the queries are. In USSDHomeController, the calls are pretty much concentrated in these two methods, and the service methods they call:

 private boolean userResponseNeeded(User sessionUser) { 
167         // todo: optimize this -- it is currently doing 2-4 DB calls on every start menu ... need to consolidate somehow to one 
168         log.info("Checking if user needs to respond to anything, either a vote or an RSVP ..."); 
169         return userManager.needsToVoteOrRSVP(sessionUser) || sessionUser.needsToRenameSelf(5) 
170             || groupManager.needsToRenameGroup(sessionUser); 
171     } 
172 
 
173     private USSDResponseTypes neededResponse(User sessionUser) { 
174 
 
175         /* Note: the sequence in which these are checked and returned sets the order of priority of responses */ 
176         /* Note: this involves around four DB pings on first menu -- extremely expensive -- need to consolidate somehow */ 
177 
 
178         if (userManager.needsToVote(sessionUser)) { 
179             log.info("User needs to vote!"); 
180             return USSDResponseTypes.VOTE; 
181         } 
182         if (userManager.needsToRSVP(sessionUser)) return USSDResponseTypes.MTG_RSVP; 
183         if (userManager.needsToRenameSelf(sessionUser)) return USSDResponseTypes.RENAME_SELF; 
184         if (groupManager.needsToRenameGroup(sessionUser)) return USSDResponseTypes.NAME_GROUP; 
185 
 
186         return USSDResponseTypes.NONE; 
187 
 
188     }

**Comment by aakil786** [comment]
looked at userResponseNeeded, and I do not see an easy way to improve on the performance. Also not sure that we need to. The following is some timing runs.

url = /ussd/start?msisdn=0826607134

cold start

<Response [200]>
1.27025103569 -- very slow after spring-boot started
<Response [200]>
0.175467967987
<Response [200]>
0.107288837433
<Response [200]>
0.105012893677
<Response [200]>
0.116461038589
<Response [200]>
0.123486995697

second run after cache expired

<Response [200]>
0.243254899979 -- fetching data as it is no longer in ehcache
<Response [200]>
0.0832030773163
<Response [200]>
0.0743660926819
<Response [200]>
0.0781478881836
<Response [200]>
0.0739979743958
<Response [200]>
0.0862832069397

I think sub 100 millisecond is more than acceptable and doubt if one will be able to improve much on that. 

The one thing I would like to change is the rsvpCache configuration. We initially made it quite short 2 minutes as we did not want the user to not get new events/votes, but after that we added code to clear the cache for all users affected by a new meeting or vote. So we should increase this value to maybe 20 minutes, as 2 minutes is very short and we might end up getting data from the DB again. We should also increase the number of objects to keep in the cache to maybe 2000 or more.
