### ISSUE TITLE
Can only create/assign one role per group

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#56]
After assigning a role to a user in a group, doing so again causes an "AlreadyExistsException". Replication steps:

1. Running Local PG, make yourself (or whatever test user you'd like) system admin via an INSERT statement in user_roles
2. Load the application, go the web interface, and click "System Admin" on the top navbar, then "groups", then pick a group that has multiple users (assume such a group created prior).
3. Via the drop downs, assign any user a role. The redirect will throw an error, but the success message "Done!" will appear, and the logs will show the group role is created and assigned.
4. Close browser and open again (to get around issue #49), and repeat steps 2 and 3, this time giving a different role to a different user.

The application will throw an error, no success message will appear, and the logs will show something like this:

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Could not add group permissions for user] with root cause

org.springframework.security.acls.model.AlreadyExistsException: Object identity 'org.springframework.security.acls.domain.ObjectIdentityImpl[Type: za.org.grassroot.core.domain.Group; Identifier: 1]' already exists
	at org.springframework.security.acls.jdbc.JdbcMutableAclService.createAcl(JdbcMutableAclService.java:99)
	at za.org.grassroot.services.GroupAccessControlManager.addUserGroupPermissions(GroupAccessControlManager.java:61)

Line 61 in GroupAccessControlManager is:

            MutableAcl acl = mutableAclService.createAcl(objectIdentity);

where objectIdentity is defined two lines above as:

ObjectIdentity objectIdentity = new ObjectIdentityImpl(Group.class, group.getId());

**Comment by lesetse** [comment]
@luke-grassroot  Please re-test when you get a chance

**Comment by luke-grassroot** [comment]
And, it works. Leaving this closed.
