### ISSUE TITLE
Distinguish among multiple logbook entries replicated for subgroups

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#57]
Use case: 

A user has a group (group X) which has multiple subgroups (X1, X2, X3). The user creates a logbook entry (A) for group X that she wants replicated in the subgroups (so we have A_X, A_X1, A_X2 ...). Later she creates a second logbook entry (B), also for group X, also replicated for subgroups (B_X, B_X1, B_X2). 

Now the user wants to view the logbook entry A and all its replicated entries, e.g., to check which subgroup entries are marked complete, but not any of the replicated entries of B. So we need a way to retrieve the set (A_X, A_X1, A_X2, A_X3) but not retrieve any of (B_X, B_X1, B_X2, B_X3). 

Note that A and B might have overlapping due dates, i.e., cannot assume they are strictly sequential. Also this needs to be possible for more than just two entries (e.g., if user has been active for a year the set of logbook entries at both X and subgroup level could easily be double digits).

**Comment by aakil786** [comment]
use getAllReplicatedEntriesForGroupAndMessage to get the specific logbook entry in all subgroups (replicated)

I am guessing the user would have retrieved all their messages for a specific group and can then select a specific logbook entry and then call the above method.
