### ISSUE TITLE
 Subgroup-wise voting totals

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#7]
Use case: If I have a group with multiple sub-groups, and I call a vote (including sub-groups), I would like to be able to see the results calculated in two ways:

1 -- What % of everyone who received it voted "yes" (i.e., a flat total)
2 -- In what % of sub-groups more than 50% voted "yes"

It would also be 'nice to have' to be able to retrieve a list of the sub-groups where the majority voted 'yes', and a list of those that voted 'no'.

**Comment by luke-grassroot** [comment]
Hmm, just checking, not sure if this is still open ... Think we discussed how it should work (i.e., how votes should count)? Looked at latest commits but couldn't immediately see if finished or not.

**Comment by aakil786** [comment]
started on the query, not quite finished yet, results at the moment look like this, still need to refine it to show percentages

group_id;group_name,message,count,numberofusersingroup
194;"level 1";"No";1;3
195;"level 2";"No";1;3
195;"level 2";"Yes";1;3
196;"level 3";"Invalid RSVP";1;2

**Comment by luke-grassroot** [comment]
Okay great. Percentages aren't a big deal, as long as web app layer can get a list/map of the results, can always do quick calcs there. But, whatever's simplest.

**Comment by aakil786** [comment]
added the percentages rounded (int) have a look at getVoteTotalsPerGroup in EventLogmanager, I think can derive what you need from the results. Let me know if you need something else.

**Comment by luke-grassroot** [comment]
Have taken a look, this looks like exactly what I need. Will reopen the issue if I run into trouble using it, but closing otherwise.
