### ISSUE TITLE
Thorough test & debug of web application sign-in

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#9]
Am receiving persistent reports of users having difficulty with sign-in. Also reported by Aakil yesterday. Need to fix this (also, to add the ability to "stay signed in on this PC").

**Comment by lesetse** [comment]
@lukes-grassroot and &aakil: what I can think of:  something could be changing the user password hash Or on the sign in page, the conversation of the phone number is messed up. The process of authentication we implemented is as follows: 1. fetch user by user name (at user fetch, the user name is the phone number with country code: ie 27xxx), 2. Verify user password

**Comment by luke-grassroot** [comment]
Interim solution, as discussed, is to use Spring Security to implement persistence ("remember me")

**Comment by aakil786** [comment]
starting

**Comment by aakil786** [comment]
added remember me functionality, test and close if nothing else is required

**Comment by luke-grassroot** [comment]
Closing for now.
